base:
  path:
    logs: "logs"
    log_config: "configs/logging_config.yml"


source:
  competition_name: "airbnb-recruiting-new-user-bookings"
  destination_path: 
    train: "data/train/source"
    test: "data/test/source"
    predict: "data/predict/source"
  params: 
    test_size: 0.2
    target: "country_destination"

  data:
    users:
      filename: 
        train_eval: "train_users_2.csv"
        predict: "test_users_2.csv"
      id_col: "id"

    sessions:
      filename: 
        train_eval: "sessions.csv"
        predict: "sessions.csv"
      id_col: "user_id"


  predict:
    data:
      path: 
      users:
        source_name: 
        user_id_col: "id"

      sessions:
        source_name: "sessions.csv"
        user_id_col: "user_id"
    
  

preprocess:
  params:
    destination:
      train_eval:
        X: "data/train/processed/X.pkl"
        target: "data/train/processed/Y.pkl"
      
      predict:
        X: "data/predict/processed/X.pkl"


model:
  train_eval:
    data:
      X_path: "data/train/processed/X.pkl"
      Y_path: "data/train/processed/Y.pkl"
    
    params:
      eval_score: "f1"
      cv_folds: 2

    save_dir: "docs/models"

  predict:
    data:
      X_path: "data/predict/processed/X.pkl"

    save_dir: "docs/models"



  

