base:
  path:
    data: "/shared/mydata.csv"
    logs: "logs"
    log_config: "adv_ds_logging.yml"
  rf_params:
    n_estimators: 400

dev:
  path_db: "sqlite:////some_dir/dev.db"
  
prod:
  path_db: "sqlite:////some_other_dir/prod.db"